// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatableController from "./datable_controller"
application.register("datable", DatableController)

import EchartsController from "./echarts_controller"
application.register("echarts", EchartsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
